"""Comprehensive Indian Festival Calendar (2020-2030) — All Religions."""
from __future__ import annotations
import pandas as pd

# (month, day, name, religion, gazetted)
_FIXED = [
    (1, 1, "New Year's Day", "National", True),
    (1, 13, "Lohri", "Sikh", False),
    (1, 14, "Makar Sankranti / Pongal", "Hindu", True),
    (1, 15, "Pongal Day 2 / Thiruvalluvar Day", "Hindu", False),
    (1, 26, "Republic Day", "National", True),
    (4, 14, "Ambedkar Jayanti", "National", True),
    (4, 14, "Baisakhi / Vaisakhi", "Sikh", True),
    (5, 1, "May Day / Labour Day", "National", True),
    (8, 15, "Independence Day", "National", True),
    (10, 2, "Gandhi Jayanti", "National", True),
    (11, 14, "Children's Day", "National", False),
    (12, 25, "Christmas", "Christian", True),
    (12, 31, "New Year's Eve", "National", False),
]

# Variable-date festivals keyed by year: list of (month, day, name, religion, gazetted)
_VARIABLE: dict[int, list[tuple]] = {
    2020: [
        (1, 29, "Basant Panchami", "Hindu", False),
        (2, 21, "Maha Shivaratri", "Hindu", True),
        (3, 10, "Holi", "Hindu", True),
        (3, 25, "Gudi Padwa / Ugadi", "Hindu", False),
        (4, 2, "Ram Navami", "Hindu", True),
        (4, 6, "Mahavir Jayanti", "Jain", True),
        (4, 10, "Good Friday", "Christian", True),
        (4, 12, "Easter Sunday", "Christian", False),
        (5, 7, "Buddha Purnima", "Buddhist", True),
        (5, 24, "Eid-ul-Fitr", "Muslim", True),
        (7, 5, "Rath Yatra", "Hindu", False),
        (7, 31, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (8, 3, "Raksha Bandhan", "Hindu", True),
        (8, 11, "Janmashtami", "Hindu", True),
        (8, 22, "Ganesh Chaturthi", "Hindu", True),
        (8, 30, "Muharram", "Muslim", True),
        (10, 17, "Navratri Start", "Hindu", False),
        (10, 25, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 30, "Milad-un-Nabi", "Muslim", True),
        (11, 4, "Karwa Chauth", "Hindu", False),
        (11, 13, "Dhanteras", "Hindu", False),
        (11, 14, "Diwali / Deepavali", "Hindu", True),
        (11, 15, "Govardhan Puja", "Hindu", False),
        (11, 16, "Bhai Dooj", "Hindu", False),
        (11, 20, "Chhath Puja", "Hindu", False),
        (11, 30, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2021: [
        (2, 16, "Basant Panchami", "Hindu", False),
        (3, 11, "Maha Shivaratri", "Hindu", True),
        (3, 29, "Holi", "Hindu", True),
        (4, 13, "Gudi Padwa / Ugadi", "Hindu", False),
        (4, 21, "Ram Navami", "Hindu", True),
        (4, 25, "Mahavir Jayanti", "Jain", True),
        (4, 2, "Good Friday", "Christian", True),
        (4, 4, "Easter Sunday", "Christian", False),
        (5, 14, "Eid-ul-Fitr", "Muslim", True),
        (5, 26, "Buddha Purnima", "Buddhist", True),
        (7, 12, "Rath Yatra", "Hindu", False),
        (7, 21, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (8, 20, "Muharram", "Muslim", True),
        (8, 22, "Raksha Bandhan", "Hindu", True),
        (8, 30, "Janmashtami", "Hindu", True),
        (9, 10, "Ganesh Chaturthi", "Hindu", True),
        (10, 7, "Navratri Start", "Hindu", False),
        (10, 15, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 19, "Milad-un-Nabi", "Muslim", True),
        (10, 24, "Karwa Chauth", "Hindu", False),
        (11, 2, "Dhanteras", "Hindu", False),
        (11, 4, "Diwali / Deepavali", "Hindu", True),
        (11, 5, "Govardhan Puja", "Hindu", False),
        (11, 6, "Bhai Dooj", "Hindu", False),
        (11, 10, "Chhath Puja", "Hindu", False),
        (11, 19, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2022: [
        (2, 5, "Basant Panchami", "Hindu", False),
        (3, 1, "Maha Shivaratri", "Hindu", True),
        (3, 18, "Holi", "Hindu", True),
        (4, 2, "Gudi Padwa / Ugadi", "Hindu", False),
        (4, 10, "Ram Navami", "Hindu", True),
        (4, 14, "Mahavir Jayanti", "Jain", True),
        (4, 15, "Good Friday", "Christian", True),
        (4, 17, "Easter Sunday", "Christian", False),
        (5, 3, "Eid-ul-Fitr", "Muslim", True),
        (5, 16, "Buddha Purnima", "Buddhist", True),
        (7, 1, "Rath Yatra", "Hindu", False),
        (7, 10, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (8, 9, "Muharram", "Muslim", True),
        (8, 11, "Raksha Bandhan", "Hindu", True),
        (8, 19, "Janmashtami", "Hindu", True),
        (8, 31, "Ganesh Chaturthi", "Hindu", True),
        (9, 26, "Navratri Start", "Hindu", False),
        (10, 5, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 9, "Milad-un-Nabi", "Muslim", True),
        (10, 13, "Karwa Chauth", "Hindu", False),
        (10, 22, "Dhanteras", "Hindu", False),
        (10, 24, "Diwali / Deepavali", "Hindu", True),
        (10, 25, "Govardhan Puja", "Hindu", False),
        (10, 26, "Bhai Dooj", "Hindu", False),
        (10, 30, "Chhath Puja", "Hindu", False),
        (11, 8, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2023: [
        (1, 26, "Basant Panchami", "Hindu", False),
        (2, 18, "Maha Shivaratri", "Hindu", True),
        (3, 8, "Holi", "Hindu", True),
        (3, 22, "Gudi Padwa / Ugadi", "Hindu", False),
        (3, 30, "Ram Navami", "Hindu", True),
        (4, 4, "Mahavir Jayanti", "Jain", True),
        (4, 7, "Good Friday", "Christian", True),
        (4, 9, "Easter Sunday", "Christian", False),
        (4, 22, "Eid-ul-Fitr", "Muslim", True),
        (5, 5, "Buddha Purnima", "Buddhist", True),
        (6, 20, "Rath Yatra", "Hindu", False),
        (6, 29, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (7, 29, "Muharram", "Muslim", True),
        (8, 30, "Raksha Bandhan", "Hindu", True),
        (9, 7, "Janmashtami", "Hindu", True),
        (9, 19, "Ganesh Chaturthi", "Hindu", True),
        (9, 28, "Milad-un-Nabi", "Muslim", True),
        (10, 15, "Navratri Start", "Hindu", False),
        (10, 24, "Dussehra / Vijayadashami", "Hindu", True),
        (11, 1, "Karwa Chauth", "Hindu", False),
        (11, 10, "Dhanteras", "Hindu", False),
        (11, 12, "Diwali / Deepavali", "Hindu", True),
        (11, 13, "Govardhan Puja", "Hindu", False),
        (11, 14, "Bhai Dooj", "Hindu", False),
        (11, 17, "Chhath Puja", "Hindu", False),
        (11, 27, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2024: [
        (2, 14, "Basant Panchami", "Hindu", False),
        (3, 8, "Maha Shivaratri", "Hindu", True),
        (3, 25, "Holi", "Hindu", True),
        (4, 9, "Gudi Padwa / Ugadi", "Hindu", False),
        (4, 17, "Ram Navami", "Hindu", True),
        (4, 21, "Mahavir Jayanti", "Jain", True),
        (3, 29, "Good Friday", "Christian", True),
        (3, 31, "Easter Sunday", "Christian", False),
        (4, 11, "Eid-ul-Fitr", "Muslim", True),
        (5, 23, "Buddha Purnima", "Buddhist", True),
        (7, 7, "Rath Yatra", "Hindu", False),
        (6, 17, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (7, 17, "Muharram", "Muslim", True),
        (8, 19, "Raksha Bandhan", "Hindu", True),
        (8, 26, "Janmashtami", "Hindu", True),
        (9, 7, "Ganesh Chaturthi", "Hindu", True),
        (9, 17, "Milad-un-Nabi", "Muslim", True),
        (10, 3, "Navratri Start", "Hindu", False),
        (10, 12, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 20, "Karwa Chauth", "Hindu", False),
        (10, 29, "Dhanteras", "Hindu", False),
        (11, 1, "Diwali / Deepavali", "Hindu", True),
        (11, 2, "Govardhan Puja", "Hindu", False),
        (11, 3, "Bhai Dooj", "Hindu", False),
        (11, 7, "Chhath Puja", "Hindu", False),
        (11, 15, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2025: [
        (2, 2, "Basant Panchami", "Hindu", False),
        (2, 26, "Maha Shivaratri", "Hindu", True),
        (3, 14, "Holi", "Hindu", True),
        (3, 30, "Gudi Padwa / Ugadi", "Hindu", False),
        (3, 31, "Eid-ul-Fitr", "Muslim", True),
        (4, 6, "Ram Navami", "Hindu", True),
        (4, 10, "Mahavir Jayanti", "Jain", True),
        (4, 18, "Good Friday", "Christian", True),
        (4, 20, "Easter Sunday", "Christian", False),
        (5, 12, "Buddha Purnima", "Buddhist", True),
        (6, 7, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (6, 27, "Rath Yatra", "Hindu", False),
        (7, 7, "Muharram", "Muslim", True),
        (8, 9, "Raksha Bandhan", "Hindu", True),
        (8, 16, "Janmashtami", "Hindu", True),
        (8, 27, "Ganesh Chaturthi", "Hindu", True),
        (9, 6, "Milad-un-Nabi", "Muslim", True),
        (9, 22, "Navratri Start", "Hindu", False),
        (10, 2, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 10, "Karwa Chauth", "Hindu", False),
        (10, 18, "Dhanteras", "Hindu", False),
        (10, 20, "Diwali / Deepavali", "Hindu", True),
        (10, 21, "Govardhan Puja", "Hindu", False),
        (10, 22, "Bhai Dooj", "Hindu", False),
        (10, 27, "Chhath Puja", "Hindu", False),
        (11, 5, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2026: [
        (1, 23, "Basant Panchami", "Hindu", False),
        (2, 15, "Maha Shivaratri", "Hindu", True),
        (3, 4, "Holi", "Hindu", True),
        (3, 19, "Gudi Padwa / Ugadi", "Hindu", False),
        (3, 21, "Eid-ul-Fitr", "Muslim", True),
        (3, 26, "Ram Navami", "Hindu", True),
        (3, 31, "Mahavir Jayanti", "Jain", True),
        (4, 3, "Good Friday", "Christian", True),
        (4, 5, "Easter Sunday", "Christian", False),
        (5, 27, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (5, 31, "Buddha Purnima", "Buddhist", True),
        (6, 16, "Rath Yatra", "Hindu", False),
        (6, 26, "Muharram", "Muslim", True),
        (8, 26, "Milad-un-Nabi", "Muslim", True),
        (8, 28, "Raksha Bandhan", "Hindu", True),
        (9, 4, "Janmashtami", "Hindu", True),
        (9, 14, "Ganesh Chaturthi", "Hindu", True),
        (10, 11, "Navratri Start", "Hindu", False),
        (10, 20, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 29, "Karwa Chauth", "Hindu", False),
        (11, 6, "Dhanteras", "Hindu", False),
        (11, 8, "Diwali / Deepavali", "Hindu", True),
        (11, 9, "Govardhan Puja", "Hindu", False),
        (11, 10, "Bhai Dooj", "Hindu", False),
        (11, 15, "Chhath Puja", "Hindu", False),
        (11, 24, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2027: [
        (2, 11, "Basant Panchami", "Hindu", False),
        (3, 6, "Maha Shivaratri", "Hindu", True),
        (3, 10, "Eid-ul-Fitr", "Muslim", True),
        (3, 22, "Holi", "Hindu", True),
        (3, 26, "Good Friday", "Christian", True),
        (3, 28, "Easter Sunday", "Christian", False),
        (4, 7, "Gudi Padwa / Ugadi", "Hindu", False),
        (4, 15, "Ram Navami", "Hindu", True),
        (4, 19, "Mahavir Jayanti", "Jain", True),
        (5, 16, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (5, 20, "Buddha Purnima", "Buddhist", True),
        (6, 6, "Rath Yatra", "Hindu", False),
        (6, 16, "Muharram", "Muslim", True),
        (8, 16, "Milad-un-Nabi", "Muslim", True),
        (8, 17, "Raksha Bandhan", "Hindu", True),
        (8, 25, "Janmashtami", "Hindu", True),
        (9, 4, "Ganesh Chaturthi", "Hindu", True),
        (10, 1, "Navratri Start", "Hindu", False),
        (10, 10, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 18, "Karwa Chauth", "Hindu", False),
        (10, 27, "Dhanteras", "Hindu", False),
        (10, 29, "Diwali / Deepavali", "Hindu", True),
        (10, 30, "Govardhan Puja", "Hindu", False),
        (10, 31, "Bhai Dooj", "Hindu", False),
        (11, 5, "Chhath Puja", "Hindu", False),
        (11, 13, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2028: [
        (1, 31, "Basant Panchami", "Hindu", False),
        (2, 23, "Maha Shivaratri", "Hindu", True),
        (2, 28, "Eid-ul-Fitr", "Muslim", True),
        (3, 11, "Holi", "Hindu", True),
        (3, 27, "Gudi Padwa / Ugadi", "Hindu", False),
        (4, 3, "Ram Navami", "Hindu", True),
        (4, 7, "Mahavir Jayanti", "Jain", True),
        (4, 14, "Good Friday", "Christian", True),
        (4, 16, "Easter Sunday", "Christian", False),
        (5, 5, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (5, 9, "Buddha Purnima", "Buddhist", True),
        (6, 4, "Muharram", "Muslim", True),
        (6, 25, "Rath Yatra", "Hindu", False),
        (8, 4, "Milad-un-Nabi", "Muslim", True),
        (8, 5, "Raksha Bandhan", "Hindu", True),
        (8, 13, "Janmashtami", "Hindu", True),
        (8, 23, "Ganesh Chaturthi", "Hindu", True),
        (9, 19, "Navratri Start", "Hindu", False),
        (9, 28, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 7, "Karwa Chauth", "Hindu", False),
        (10, 15, "Dhanteras", "Hindu", False),
        (10, 17, "Diwali / Deepavali", "Hindu", True),
        (10, 18, "Govardhan Puja", "Hindu", False),
        (10, 19, "Bhai Dooj", "Hindu", False),
        (10, 24, "Chhath Puja", "Hindu", False),
        (11, 2, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2029: [
        (1, 20, "Basant Panchami", "Hindu", False),
        (2, 12, "Maha Shivaratri", "Hindu", True),
        (2, 16, "Eid-ul-Fitr", "Muslim", True),
        (2, 28, "Holi", "Hindu", True),
        (3, 16, "Gudi Padwa / Ugadi", "Hindu", False),
        (3, 23, "Ram Navami", "Hindu", True),
        (3, 28, "Mahavir Jayanti", "Jain", True),
        (3, 30, "Good Friday", "Christian", True),
        (4, 1, "Easter Sunday", "Christian", False),
        (4, 24, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (5, 25, "Muharram", "Muslim", True),
        (5, 28, "Buddha Purnima", "Buddhist", True),
        (6, 14, "Rath Yatra", "Hindu", False),
        (7, 24, "Milad-un-Nabi", "Muslim", True),
        (8, 24, "Raksha Bandhan", "Hindu", True),
        (9, 1, "Janmashtami", "Hindu", True),
        (9, 11, "Ganesh Chaturthi", "Hindu", True),
        (10, 8, "Navratri Start", "Hindu", False),
        (10, 17, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 26, "Karwa Chauth", "Hindu", False),
        (11, 3, "Dhanteras", "Hindu", False),
        (11, 5, "Diwali / Deepavali", "Hindu", True),
        (11, 6, "Govardhan Puja", "Hindu", False),
        (11, 7, "Bhai Dooj", "Hindu", False),
        (11, 12, "Chhath Puja", "Hindu", False),
        (11, 21, "Guru Nanak Jayanti", "Sikh", True),
    ],
    2030: [
        (2, 8, "Basant Panchami", "Hindu", False),
        (2, 5, "Eid-ul-Fitr", "Muslim", True),
        (3, 3, "Maha Shivaratri", "Hindu", True),
        (3, 18, "Holi", "Hindu", True),
        (4, 4, "Gudi Padwa / Ugadi", "Hindu", False),
        (4, 12, "Ram Navami", "Hindu", True),
        (4, 13, "Eid-ul-Adha (Bakr-Eid)", "Muslim", True),
        (4, 16, "Mahavir Jayanti", "Jain", True),
        (4, 19, "Good Friday", "Christian", True),
        (4, 21, "Easter Sunday", "Christian", False),
        (5, 14, "Muharram", "Muslim", True),
        (5, 17, "Buddha Purnima", "Buddhist", True),
        (7, 4, "Rath Yatra", "Hindu", False),
        (7, 14, "Milad-un-Nabi", "Muslim", True),
        (8, 13, "Raksha Bandhan", "Hindu", True),
        (8, 21, "Janmashtami", "Hindu", True),
        (8, 31, "Ganesh Chaturthi", "Hindu", True),
        (9, 28, "Navratri Start", "Hindu", False),
        (10, 7, "Dussehra / Vijayadashami", "Hindu", True),
        (10, 15, "Karwa Chauth", "Hindu", False),
        (10, 24, "Dhanteras", "Hindu", False),
        (10, 26, "Diwali / Deepavali", "Hindu", True),
        (10, 27, "Govardhan Puja", "Hindu", False),
        (10, 28, "Bhai Dooj", "Hindu", False),
        (11, 1, "Chhath Puja", "Hindu", False),
        (11, 10, "Guru Nanak Jayanti", "Sikh", True),
    ],
}


def get_indian_festival_calendar(start_year: int = 2020, end_year: int = 2030) -> pd.DataFrame:
    """Return a DataFrame of Indian festivals from *start_year* to *end_year*."""
    rows: list[dict] = []
    for year in range(start_year, end_year + 1):
        # Fixed-date festivals
        for month, day, name, religion, gazetted in _FIXED:
            try:
                rows.append({
                    "Date": pd.Timestamp(year, month, day),
                    "Festival": name,
                    "Religion": religion,
                    "Is_Gazetted": gazetted,
                })
            except ValueError:
                pass
        # Variable-date festivals
        for month, day, name, religion, gazetted in _VARIABLE.get(year, []):
            try:
                rows.append({
                    "Date": pd.Timestamp(year, month, day),
                    "Festival": name,
                    "Religion": religion,
                    "Is_Gazetted": gazetted,
                })
            except ValueError:
                pass
    df = pd.DataFrame(rows)
    if df.empty:
        return pd.DataFrame(columns=["Date", "Festival", "Religion", "Is_Gazetted"])
    df = df.sort_values("Date").drop_duplicates(subset=["Date", "Festival"]).reset_index(drop=True)
    df["Month"] = df["Date"].dt.month
    df["Month_Name"] = df["Date"].dt.month_name()
    df["Day_Name"] = df["Date"].dt.day_name()
    df["Year"] = df["Date"].dt.year
    return df
